from normalize import normalize_phrase

referentiel = {
    "DSOP_METHODES_Validation_conjointe_MEDEVAC_Filiales-MOS-IMA_Niort_VF": "Tous_Mode_operatoire_Illimitee_06_03_2024_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Prendre une decision medicale de transport medicalise_VF": "Tous_Procedure_metier_Illimitee_04_12_2024_Decision_medicale_Dossier_medical",
    "DSOP_METHODES_Equipes_MEDEVAC_gestion_des_risques_lies_a_la_fatigue_VF": "Tous_Mode_operatoire_Illimitee_17_07_2024_Application_garanties_Dossier_medical",
    "DSOP_Méthodes_Activation_de_Encadrement_Medical_et_operationnel_Astreinte_VF": "Tous_Procedure_metier_Illimitee_09_12_2024_Application_des_garanties_Dossier_medical",
    "DSOP_METHODES_Scoring risque Medico-Operationnel_VF": "Tous_Procedure_metier_Illimitee_27_10_2023_Ouverture_Dossier_Etranger_medical",
    "DSOP_Méthodes_Process MGEN FMHO et orientation medicale continent americain et 8 pays_VF": "Tous_Procedure_metier_Illimitee_Application_garanties_Dossier_medical_MGEN",
    "DSOP_Méthodes_Mandater GEOS_VF": "Tous_Procedure_metier_Illimitee_Application_garanties_Dossier_medical",
    "DSOP_Méthodes_Organisation des transmissions Operationnelles et Medicales – Briefs Medicaux_VF": "OME_DMEG_BTA_Organisation_plateau_Depuis_2021_17_05_2021_Decision_Service_Medical_Patient_en_attente_DSM",
    "DSOP_METHODES_Equipes Medicales – Documents pour le transport patient depuis le Portugal_VF": "Tous_Mode_operatoire_Illimitee_19_12_2023_Montage_MEDEVAC_Dossier_medical",
    "DSOP_Méthodes_Delivrer une attestation assistance contrats Mobilite internationale_VF": "Tous_Procedure_metier_Illimitee_Application_garanties_Attestation_d_assistance",
    "DSOP_METHODES_Alerte dossiers lourds frais medicaux_VF": "Tous_Procedure_metier_Illimitee_20_07_2023_Application_garanties_Dossier_medical",
    "DSOP_Méthodes_Envoi de medicaments lunettes ou protheses_VF": "Tous_Mode_operatoire_Illimitee_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Envoi_des_rapports_medicaux_au_CNSE_VF": "OME_Procedure_metier_Illimitee_25_07_2023_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Health-E_VF": "Tous_Mode_operatoire_Illimitee_20_12_2024_Application_garanties_Dossier_medical",
    "DSOP_METHODES_SMART_Synthese_Medicale_Analysant_les_Rates_Transport_MEDEVAC_VF": "Tous_Procedure_metier_Illimitee_27_01_2022_Application_garanties_Dossier_medical",
    "DSOP_METHODES_OME_Gestion_des_dossiers_Corporate_VIP_Mediatiques_VF": "Tous_Procedure_metier_Illimitee_20_11_2023_Application_garanties_Dossier_medical_expatrie",
    "DSOP_METHODES_Codification_des_flux_Frais_medicaux_VF": "Tous_Procedure_metier_Illimitee_28_06_2023_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Recherche de la place arrivee pour un patient_VF": "Tous_Procedure_metier_Illimitee_19_09_2022_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Avance de fonds des frais medicaux _VF": "Tous_Procedure_metier_Illimitee_25_07_2023_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Changement Unite Bureautique OME_VF": "Tous_Mode_operatoire_Illimitee_08_08_2023_Ouverture_poste_travail_Changement_d_affectation",
    "DSOP_METHODES_Organiser_un_transport_medicalise_les_essentiels_VF": "Tous_Procedure_metier_Illimitee_02_03_2023_Application_garanties_Dossier_medical",
    "DSOP_METHODES_OME_Reservation_train_par_le_BTA_VF": "Tous_Mode_operatoire_Illimitee_29_02_2024_Application_garanties_Dossier_medical",
    "DSOP_Méthodes_Gestion des dossiers Frais Medicaux survenance Portugal_VF": "Tous_Procedure_metier_Illimitee_17_12_2020_Gestion_Dossier_medical",
    "DSOP_METHODES_OME_Fiche_BTA_pas_a_pas_VF": "Tous_Mode_operatoire_Illimitee_06_12_2024_Application_garanties_Dossier_medical",
    "DSOP_METHODES_INCAD_MEDIF_MEDA_FFT_NACA_VF": "Tous_Mode_operatoire_Illimitee_27_05_2024_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Activation_du_Correspondant_Medical_et_securisation_des_MEDEVAC_VF": "Tous_Procedure_metier_Illimitee_02_10_2023_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Liste des pays soumis a une vigilance financiere_VF": "Tous_Procedure_metier_Illimitee_13_03_2023_Ouverture_Dossier_survenance_etranger",
    "DSOP_Méthodes_Delivrer une attestation d’intervention dossiers medicaux_VF": "Tous_Procedure_metier_Illimitee_25_02_2020_Renseignement_Dossier_medical",
    "DSOP_METHODES_Organiser une medicalisation evenementielle_VF": "Tous_Mode_operatoire_Illimitee_01_06_2023_Application_garanties_Demande_de_medicalisation",
    "DSOP_METHODES_MEO_Ambulances_MEDEVAC_VF": "Tous_Mode_operatoire_Illimitee_09_12_2024_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Decision du Service Medical - Avion Sanitaire_VF": "Tous_Procedure_metier_Illimitee_02_01_2025_Application_garanties_Dossier_medical",
    "DSOP_Méthodes_UNEO Teleconsultation_VF": "Tous_Procedure_metier_Illimitee_Application_garanties_Service_reserve_aux_beneficiaires_UNEO_a_l_etranger_contrats_MONDE_PASS_OPTIMONDE_OPTIMONDE_SANTE_INTERNATIONALE_NOUVELLE_CALEDONIE",
    "DSOP_Méthodes_Declarer et traiter un dysfonctionnement Plateau Operations Medicales_VF": "Tous_Procedure_metier_Illimitee_02_01_2025_Application_des_garanties_Dossier_medical",
    "DSOP_METHODES_Reponse_a_une_demande_de_donnees_medicales_et_confidentielles_VF": "Tous_Procedure_metier_Illimitee_29_11_2024_Application_garanties_Dossier_medical",
    "DSOP_Méthodes_Interactions Sante - Medical_VF": "DOMSBV_Mode_Operatoire_Illimite_17_12_2024_Ouverture_Reception_d_un_appel_Sante_sur_le_plateau_OME",
    "DSOP_METHODES_Gestion_des_prestataires_Ambulance_VSL_TAXI_pour_les_MEDEVAC_VF": "Tous_Procedure_metier_Illimitee_06_02_2024_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Attestation_assurance_FMHO_equipes_MEDEVAC_VF": "Tous_Procedure_metier_Illimitee_07_12_2022_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Bipper_les_equipes_MEDEVAC_VF": "Tous_Mode_operatoire_Illimitee_15_06_2022_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Criteres de choix hotel pour les equipes medicales_VF": "Tous_Procedure_metier_Illimitee_12_03_2024_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Aide_a_la_decision_pour_une_Air_Ambulance_en_situation_aigue_VF": "Tous_Procedure_metier_Illimitee_24_03_2021_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Priorisation_des_equipes_MEDEVAC_VF": "Tous_Procedure_metier_Illimitee_21_05_2024_Application_garanties_Dossier_medical",
    "DSOP_Méthodes_PIMS_DSM_Medicale_VF": "OME_PIMS_DMEG_Mode_Operatoire_Depuis_le_01_11_2024_01_11_2024_Decision_Service_Medical_Sollicitation_de_la_PIMS_pour_DSM",
    "DSOP_Méthodes_Justificatifs et paiements anticipes_VF": "Tous_Procedure_Metier_Illimitee_Application_des_garanties_Dossier_medical",
    "DSOP_METHODES_Briefing medical des equipes medicales de transport de Montreuil_VF": "Tous_Procedure_metier_Illimitee_13_10_2021_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Teleconsultation - Utilisation Xperteye_VF": "Tous_Mode_operatoire_Illimitee_10_09_2024_Application_garanties_Demande_teleconsultation",
    "DSOP_Méthodes_Specificites vols Air France_VF": "Plateau_OME_Mode_Operatoire_Illimite_03_01_2025_Mise_en_oeuvre_moyen_Transport_via_vol_Air_France",
    "DSOP_METHODES_Passer une commande avec la E-Carte Bancaire MEDEVAC_VF": "Tous_Mode_operatoire_Illimitee_20_03_2024_Application_garanties_Dossier_medical",
    "DSOP_Méthodes_Utilisation et Reservation CDS pour un transporteur medical - MCS & HIGGINS_VF": "Tous_Mode_operatoire_Illimitee_02_03_2023_Application_garanties_Reservation_d_un_hotel_via_l_outil_CDS",
    "DSOP_Méthodes_Alarme_SERELIA_Prise_en_charge_medicale_VF": "Plateau_OME_Procedure_metier_Illimitee_12_09_2024_Decision_medicale_Appel_SERELIA_transfere",
    "DSOP_Méthodes_MOP_Connexion au Portail My Global Support pour adherents MGEN_VF": "Tous_Mode_operatoire_Depuis_le_13_10_2023_Renseignement_Medical",
    "DSOP_METHODES_MEDEVAC_Temps_de_trajets_Region_Parisienne_VF": "Tous_Mode_operatoire_Illimitee_11_09_2024_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Envoi securise de Donnees Medicales et Confidentielles_VF": "Tous_Mode_operatoire_Illimitee_17_01_2024_Application_garanties_Dossier_medical",
    "DSOP_METHODES_Traitement sollicitations DGS_VF": "Tous_Procedure_metier_Illimitee_30_05_2024_Application_garanties_Dossier_medical",
    "DSOP_Méthodes_Traitement sollicitations UNIHA_VF": "Tous_Procedure_metier_Illimitee_05_09_2024_Application_garanties_Dossier_UNIHA",
    "DSOP_Méthodes_Activité professionnelle_VF": "Fait_generateur_ACTIVITE_PROFESSIONNELLE",
    "DSOP_Méthodes_Livraison Higgins du 17 janvier 2023_VF": "Livraison_Higgins_V3_2_1_du_17_janvier_2023",
    "DSOP_Méthodes_Annuler une imputation_VF": "Annuler_une_imputation",
    "DSOP_Méthodes_Rembourser après décès du bénéficiaire_VF": "Rembourser_apres_deces_du_beneficiaire_a_l_OSBV",
    "DSOP_Méthodes_Décès_VF": "Fait_generateur_Deces",
    "DSOP_Méthodes_Livraison Higgins V3.9_VF": "Livraison_Higgins_V3_9_du_15_octobre_2024",
    "DSOP_Méthodes_Evènement particulier": "La_zone_Evenement_particulier_sur_Higgins_Sante",
    "DSOP_Méthodes_Le dossier Refus_VF": "Le_Dossier_refus",
    "DSOP_Méthodes_Garanties Conseil_Information_VF": "Garanties_Conseil_et_Information",
    "DSOP_Méthodes_Mémo Renseignements_VF": "Memo_Renseignements",
    "DSOP_Méthodes_Trame Mail libre Unéo_VF": "Trame_Mail_libre_Uneo",
    "DSOP_Méthodes_Faux appel_VF": "Tracer_un_Faux_appel",
    "DSOP_Méthodes_Transférer l'appel + le dossier_VF": "Transferer_l_appel_et_le_dossier",
    "DSOP_Méthodes_E-réputation_VF": "Service_E_Reputation",
    "DSOP_Méthodes_Période d'application des garanties_VF": "Periode_d_application_des_garanties",
    "DSOP_Méthodes_Evolutions récentes de l'outil_VF": "Evolutions_Higgins_Sante",
    "DSOP_Méthodes_Enrôlement_ Réceptionner le fichier quotidien_VF": "Enrolement_Receptionner_le_fichier_quotidien",
    "DSOP_Méthodes_Lettre-chèque non reçue_VF": "Traiter_une_demande_de_Lettre_cheque_non_recue",
    "DSOP_Méthodes_Contexte familial du demandeur_VF": "CONTEXTE_FAMILIAL_DU_DEMANDEUR",
    "DSOP_Méthodes_ADO Mobilité Sénior_VF": "MAIF_Formule_ADO_Mobilite_Senior",
    "DSOP_Méthodes_Trait d'union_VF": "Partenaire_Trait_d_union",
    "DSOP_Méthodes_Service_ Frais mise en relation_VF": "Service_Frais_mise_en_relation",
    "DSOP_Méthodes_Etiquettes_VF": "La_zone_Etiquettes",
    "DSOP_Méthodes_Ouverture dossiers_ Sourds et Malentendants_VF": "Reception_des_demandes_pour_les_sourds_et_malentendants",
    "DSOP_Méthodes_Bouton  Contrats_VF": "Fonctionnalite_du_bouton_CONTRATS",
    "DSOP_Méthodes_Justificatif Décidé_VF": "Definition_Justificatif_Decide",
    "DSOP_METHODES_Garantie Garde_VF": "Garanties_Garde",
    "DSOP_Méthodes_Service Retour à l'emploi_VF": "Service_Retour_a_l_emploi",
    "DSOP_METHODES_Fax_E-mail_VF": "Fax_E_mail",
    "DSOP_Méthodes_ECUREUIL SANTE_VF": "ECUREUIL_SANTE",
    "DSOP_Méthodes_ADO MAIF consignes gestion_VF": "ADO_MAIF_Consignes_Gestion",
    "DSOP_Méthodes_Ouverture dossiers Obsèques_VF": "Ouvrir_un_dossier_Obseques",
    "DSOP_Méthodes_Souscripteur en _Vigilance__VF": "Le_Souscripteur_en_VIGILANCE",
    "DSOP_Méthodes_Renseignement Médical PMS_VF": "Renseignement_Medical_PMS",
    "DSOP_Méthodes_Domplus_VF": "Plateforme_Partenaires_Clients_Domplus",
    "DSOP_Méthodes_VIP_VF": "Identifier_un_VIP",
    "DSOP_Méthodes_Créer une tâche_VF": "Creer_une_tache",
    "DSOP_Méthodes_Modalités de prise en charge_VF": "Modalites_de_prise_en_charge",
    "DSOP_Méthodes_Service Conduite au travail_VF": "Service_Conduite_au_travail",
    "DSOP_Méthodes_Recueil de consentement - collecte et traitement des données de santé_VF": "Recueil_de_consentement_Collecte_et_traitement_des_donnees_de_sante",
    "DSOP_METHODES_GENERIQUE_Statuts_telephoniques_WIKI_VF": "Statuts_telephoniques_sur_Higgins_Sante",
    "DSOP_Méthodes_Fichier Obligatoire avec vérification des droits_VF": "Fichier_Obligatoire_avec_verification_des_droits",
    "DSOP_Méthodes_Mesures conservatoires_VF": "Les_mesures_conservatoires",
    "DSOP_Méthodes_Onglet Commande _ détails_VF": "Onglet_Commande_Details",
    "DSOP_Méthodes_Renseignement Assistance Info contrat_VF": "Renseignement_Assistance_Info_contrat",
    "DSOP_Méthodes_Qualité Relation Client (QRC)_VF": "Qualite_Relation_Client_QRC",
    "DSOP_Méthodes_Cellule Appels Sortants Réseaux_VF": "Activites_Cellule_Appels_Sortants_Reseau",
    "DSOP_Méthodes_Souscripteur crée_VF": "Souscripteur_cree",
    "DSOP_Méthodes_Enveloppe financière_VF": "L_enveloppe_financiere",
    "DSOP_Méthodes_La Réunion_VF": "Renseigner_une_adresse_a_La_Reunion",
    "DSOP_Méthodes_Attestations_VF": "Repondre_a_une_demande_d_Attestation",
    "DSOP_Méthodes_Transférer un appel_VF": "Transferer_un_appel",
    "DSOP_Méthodes_Répit_VF": "Fait_generateur_Repit",
    "DSOP_Méthodes_BTA_VF": "BTA_pour_l_OSBV",
    "DSOP_Méthodes_RGPD et enregistrement des appels_VF": "RGPD_et_enregistrement_des_appels_sur_Higgins_Sante",
    "DSOP_Méthodes_Direction Flux Opérationnels_VF": "Direction_Flux_Operationnels",
    "DSOP_Méthodes_Liste de résultats_VF": "LISTE_DE_RESULTATS",
    "DSOP_Méthodes_BPCE Assurance (BPCEA)_VF": "BPCE_Assurance_BPCEA",
    "DSOP_Méthodes_Hotel Hébergement_VF": "HOTEL_HEBERGEMENT",
    "DSOP_Méthodes_Back Office_VF": "Activites_Back_Office",
    "DSOP_Méthodes_Enrôlement_VF": "Clients_Formules_beneficiant_de_l_enrolement",
    "DSOP_Méthodes_Comportement inapproprié envers un intervenant_VF": "Comportement_inapproprie_envers_un_intervenant_a_l_OSBV",
    "DSOP_Méthodes_Stimulus_VF": "Stimulus",
    "DSOP_Méthodes_Chimio-radiothérapie_VF": "Evenement_CHIMIO_RADIOTHERAPIE",
    "DSOP_Méthodes_Modification d'une commande_VF": "Modification_d_une_commande",
    "DSOP_Méthodes_Activité Evaluations Sociales_VF": "Activite_Evaluations_Sociales",
    "DSOP_Méthodes_Rembourser une facture Services à la Personne (SAP)_VF": "Rembourser_une_facture_Services_a_la_Personne_SAP",
    "DSOP_Méthodes_Partenaires_VF": "Partenaires_IMA",
    "DSOP_Méthodes_Emettre un appel_VF": "Emettre_un_appel",
    "DSOP_Méthodes_RAPPEL MEO_VF": "RAPPEL_MEO",
    "DSOP_Méthodes_Trame Mail libre_ Dossiers Sentinelle_VF": "Trame_Mail_libre_Dossiers_Sentinelle",
    "DSOP_Méthodes_Solliciter les Ergo-TSO_VF": "Solliciter_les_Ergos_TSO",
    "DSOP_Méthodes_Suivi Prestataires Réseau Domicile_VF": "Realiser_un_suivi_de_Prestataire",
    "DSOP_Méthodes_Va & Vient_VF": "Fonctionnalite_de_l_icone_Va_Vient",
    "DSOP_Méthodes_Historique des modifications d'une commande_VF": "Onglet_Historique_des_modifications_d_une_commande",
    "DSOP_Méthodes_Mémo Transport_VF": "Memo_Transports",
    "DSOP_Méthodes_Sourds et Malentendants Traitement via centre d'appels_VF": "Sourds_et_Malentendants_Traitement_via_centre_d_appels",
    "DSOP_Méthodes_BPCE Vie & BPCEA_VF": "Le_groupe_BPCE",
    "DSOP_Méthodes_Moyen Avion Place Assise_VF": "Moyen_Avion_Place_Assise",
    "DSOP_Méthodes_ADO MAIF consignes application_VF": "ADO_MAIF_Consignes_Application",
    "DSOP_METHODES_Déclaration d'anomalies_VF": "Declaration_d_anomalies_sur_Higgins_Sante",
    "DSOP_Méthodes_Mutuelle Inconnue_VF": "Ouvrir_un_dossier_en_Mutuelle_Inconnue",
    "DSOP_Méthodes_Service Portage de Repas_VF": "Service_Portage_de_Repas",
    "DSOP_Méthodes_Moyen Véh de location_VF": "Moyen_Vehicule_de_location",
    "DSOP_METHODES_Aide à la naissance_Acquisition des premiers gestes_VF": "Prestation_Aide_a_la_Naissance_acquisition_des_premiers_gestes",
    "DSOP_Méthodes_Service_ Aide aux démarches_VF": "Service_Aide_aux_demarches",
    "DSOP_Méthodes_Bénéficiaires d'un remboursement_VF": "Definition_Beneficiaires_d_un_remboursement",
    "DSOP_Méthodes_Trame mail libre _ Demande du nombre d'heures effectuées_VF": "Trame_Mail_libre_Demande_du_nombre_d_heures_effectuees",
    "DSOP_Méthodes_Fichier Indicatif_VF": "Fichier_Indicatif",
    "DSOP_Méthodes_UNEO-IMAU_VF": "IMAU_UNEO",
    "DSOP_Méthodes_Paiement par virement_VF": "Effectuer_un_paiement_par_virement",
    "DSOP_Méthodes_Garanties avec spécificités MH_VF": "MH_AUXIA_Garanties_avec_specificites",
    "DSOP_Méthodes_Direction Support aux Opérations_VF": "Direction_Support_aux_OPerations",
    "DSOP_Méthodes_DMeG - Direction Médicale_VF": "DMeG_Direction_Medicale",
    "DSOP_Méthodes_Réseau Domicile_VF": "Le_Reseau_Domicile",
    "DSOP_Méthodes_Absence fichier_VF": "SOUSCRIPTEUR_ABSENT_DU_FICHIER",
    "DSOP_Méthodes_Synthèse dossier_VF": "Onglet_Synthese_dossier",
    "DSOP_Méthodes_Mobilité Douce_VF": "Mobilite_Douce_a_l_OSBV",
    "DSOP_Méthodes_Trame mail libre _ Relance mission_VF": "Trame_Mail_libre_Relance_mission",
    "DSOP_Méthodes_Aide à l'emploi - Moyen Emploi licenciement_VF": "MOYEN_EMPLOI_LICENCIEMENT",
    "DSOP_Méthodes_Définitions et principes de la protection des données_VF": "Definitions_et_principes_de_la_protection_des_donnees_a_l_OSBV",
    "DSOP_Méthodes_Vétophonie_VF": "Partenaire_Vetophonie",
    "DSOP_Méthodes_La zone Coûts_VF": "La_zone_Couts",
    "DSOP_Méthodes_Délai de tolérance_VF": "DELAI_DE_TOLERANCE",
    "DSOP_Méthodes_Service Acco examens médicaux_VF": "Service_Acco_aux_examens_medicaux",
    "DSOP_Méthodes_Créer un intervenant non-référencé_VF": "Creer_un_intervenant_non_reference_pour_commande_FA",
    "DSOP_Méthodes_RAPPEL ADM_VF": "RAPPEL_ADM",
    "DSOP_Méthodes_Rechercher un intervenant FA_VF": "Rechercher_un_intervenant_FA",
    "DSOP_Méthodes_Livraison Higgins V3.8_VF": "Livraison_Higgins_V3_8_du_21_mai_2024",
    "DSOP_METHODES_Dispositif Sentinelle_VF": "Le_Dispositif_Sentinelle",
    "DSOP_Méthodes_Calcul Prise en charge Prestations à domicile_VF": "Calcul_Prise_en_charge_Prestations_a_domicile",
    "DSOP_Méthodes_Bandeau CTI_VF": "Bandeau_CTI_sur_Higgins_Sante",
    "DSOP_Méthodes_Carences Taxis 1er niveau_VF": "Traiter_une_carence_Taxi_de_1er_niveau",
    "DSOP_Méthodes_Dispositif Colibri_VF": "ADO_MAIF_Dispositif_Colibri_a_l_OSBV",
    "DSOP_Méthodes_Cybersécurité_VF": "Garanties_Cybersecurite",
    "DSOP_Méthodes_Centre de gestion intégré_VF": "Centre_de_Gestion_Integre",
    "DSOP_Méthodes_Aide à l'emploi - Moyen Aide à l'emploi_VF": "Moyen_Aide_a_l_emploi",
    "DSOP_Méthodes_Garanties Décès MH_VF": "MH_AUXIA_Garanties_Deces",
    "DSOP_Méthodes_Qualité de l'appelant_VF": "La_zone_Qualite_de_l_appelant",
    "DSOP_Méthodes_Téléphonie_VF": "Utiliser_la_telephonie",
    "DSOP_Méthodes_Fichier obligatoire_VF": "Fichier_Obligatoire",
    "DSOP_Méthodes_Service_ Forfait Téléassistance_VF": "Service_Forfait_Teleassistance",
    "DSOP_Méthodes_Traitement différé_VF": "Creer_une_tache_Traitement_differe",
    "DSOP_Méthodes_Maladie_VF": "Fait_generateur_Maladie",
    "DSOP_Méthodes_Renseignement Assurance_ Orientation mutuelle_VF": "Renseignement_Assurance_Orientation_mutuelle",
    "DSOP_Méthodes_Fonctionnalités à partir d'un E-mail entrant_VF": "Fonctionnalites_a_partir_d_un_E_mail_entrant",
    "DSOP_Méthodes_Enrôlement_ Visualiser les bénéficiaires à contacter_VF": "Enrolement_Visualiser_les_beneficiaires_a_contacter",
    "DSOP_Méthodes_Les SMS_Mails automatiques avec spécificités MH_VF": "MH_AUXIA_SMS_et_Mails_automatiques_specifiques",
    "DSOP_Méthodes_Justificatif Accepté_VF": "Definition_Justificatif_Accepte",
    "DSOP_Méthodes_Bouton  Fichier_VF": "Fonctionnalite_du_bouton_FICHIER",
    "DSOP_Méthodes_I-Protego_VF": "Partenaire_I_Protego",
    "DSOP_Méthodes_Créer tâche (hors dossier)_VF": "CREER_TACHE_HORS_DOSSIER",
    "DSOP_Méthodes_Délai de demande d'assistance_VF": "DELAI_DE_DEMANDE_D_ASSISTANCE",
    "DSOP_Méthodes_Enveloppes_VF": "Les_Enveloppes_de_services",
    "DSOP_Méthodes_ADO MAIF consignes ouverture_VF": "ADO_MAIF_Consignes_Ouverture",
    "DSOP_Méthodes_Livraison Higgins V3.10_VF": "Livraison_Higgins_V3_10_du_27_novembre_2024",
    "DSOP_Méthodes_Requalifier un courrier_VF": "Requalifier_un_courrier",
    "DSOP_METHODES_DI TAXI_VF": "DI_TAXI",
    "DSOP_Méthodes_Transfert vers IMATECH_VF": "Transferer_un_service_Renseignement_vers_IMATECH",
    "DSOP_Méthodes_Fichier échu_VF": "Fichier_Echu",
    "DSOP_Méthodes_Conicom_VF": "Conicom",
    "DSOP_Méthodes_Flux inexploitable autres Grand Comptes_VF": "Flux_inexploitable_autres_Grands_Comptes",
    "DSOP_Méthodes_Imputer un justificatif_VF": "Imputer_un_justificatif",
    "DSOP_METHODES_Attestation Assistance_VF": "Generer_une_Attestation_d_Assistance",
    "DSOP_Méthodes_Les Actus dossier_VF": "Codifications_des_Actus_dossiers",
    "DSOP_METHODES_Assistance Cumulative_VF": "Assistance_cumulative_a_l_OSBV",
    "DSOP_METHODES_Envoyer un document_VF": "Envoyer_un_document",
    "DSOP_Méthodes_Service_ Gardiennage du Dom_VF": "Service_Gardiennage_du_Domicile",
    "DSOP_Méthodes_Trames mails_VF": "Les_Trames_Mails",
    "DSOP_Méthodes_Ouverture dossiers Maladie Longue Durée_VF": "Ouverture_dossier_Maladie_Longue_Duree",
    "DSOP_Méthodes_Service_ Déménagement_VF": "Service_Demenagement",
    "DSOP_Méthodes_Réception FDL_VF": "Reception_FDL",
    "DSOP_Méthodes_Suspicion de fausse déclaration_VF": "Dispositif_pour_Suspicion_de_fausse_declaration",
    "DSOP_Méthodes_Login_VF": "Login_Higgins_Sante",
    "DSOP_Méthodes_Fiche de Liaison incomplète_VF": "MAIF_Fiche_de_Liaison_incomplete",
    "DSOP_Méthodes_Renseignement Médical Déplacement_VF": "Renseignement_Medical_Deplacement",
    "DSOP_Méthodes_Service_ Bilan social_VF": "Service_Bilan_social",
    "DSOP_Méthodes_TMSkinergo_VF": "Partenaire_TMSkinergo",
    "DSOP_Méthodes_Gestion des courriers CNP_VF": "Gestion_des_courriers_CNP_Assur_Protection_Sociale",
    "DSOP_Méthodes_Corbeille des Tâches_VF": "Corbeille_des_Taches",
    "DSOP_Méthodes_Trame Comportement Inapproprié_VF": "Trame_Comportement_Inapproprie_envers_un_intervenant",
    "DSOP_Méthodes_Client Groupement de mutuelles_VF": "CLIENT_GROUPEMENT_DE_MUTUELLES",
    "DSOP_Méthodes_Recherche Client_VF": "La_Recherche_Client_a_l_OSBV",
    "DSOP_Méthodes_Absence de n° de LR_VF": "Acceder_a_la_liste_des_ndeg_de_LR",
    "DSOP_Méthodes_Raccrocher un appel_VF": "Raccrocher_un_appel",
    "DSOP_Méthodes_Refuser la Prise en charge d'un justificatif_VF": "Refuser_la_Prise_en_charge_d_un_justificatif",
    "DSOP_Méthodes_Motif de REFUS_ Sujet non assistable_VF": "Motif_de_REFUS_pour_Sujet_non_assistable",
    "DSOP_Méthodes_Livraison Higgins du 06 juin 2023_VF": "Livraison_Higgins_V3_4_du_06_juin_2023",
    "DSOP_Méthodes_Décès imminent_VF": "Evenement_Deces_imminent",
    "DSOP_Méthodes_Ouverture sur demande DOMPLUS_VF": "Ouverture_dossier_sur_demande_DOMPLUS",
    "DSOP_Méthodes_Abandonner la création d'une tâche_VF": "Abandonner_la_creation_d_une_tache",
    "DSOP_Méthodes_Accompagnement Hospitalisation_VF": "Service_Acco_Hospitalisation",
    "DSOP_Méthodes_Alixio Mobilité_VF": "Alixio_Mobilite",
    "DSOP_Méthodes_Service Conduite Extrascolaire_VF": "Service_Conduite_Extrascolaire",
    "DSOP_Méthodes_Mise à jour enveloppe financière_VF": "Mise_a_jour_de_l_enveloppe_financiere",
    "DSOP_Méthodes_Renseignement Prestataire_VF": "Renseignement_Prestataire",
    "DSOP_METHODES_Garanties Soutien Scolaire_VF": "Garanties_Soutien_scolaire",
    "DSOP_Méthodes_Déplacement Restreint_VF": "Deplacement_Restreint",
    "DSOP_Méthodes_Date de survenance_VF": "Date_de_survenance",
    "DSOP_Méthodes_Coaching conduite_VF": "Service_Coaching_conduite",
    "DSOP_Méthodes_Correspondants_VF": "Correspondants",
    "DSOP_Méthodes_DI Mobile Santé_VF": "DI_Mobile_Sante",
    "DSOP_Méthodes_Montant seuil pour prise en charge sans données_VF": "Montant_seuil_pour_prise_en_charge_sans_donnees",
    "DSOP_Méthodes_Livraison Higgins V3.7 du 19 mars 2024_VF": "Livraison_Higgins_V3_7_du_19_mars_2024",
    "DSOP_Méthodes_Carnet d'adresses_VF": "Carnet_d_adresses",
    "DSOP_Méthodes_Traiter une tâche_VF": "Traiter_une_tache",
    "DSOP_Méthodes_Création d'une commande_VF": "Creation_d_une_commande",
    "DSOP_Méthodes_Utilisation du poste téléphonique_VF": "Utiliser_le_poste_telephonique",
    "DSOP_Méthodes_Indisponibilité de l'aidant_VF": "Evenement_Indisponibilite_de_l_aidant",
    "DSOP_Méthodes_Modifier date échéance_VF": "Modifier_la_date_d_echeance",
    "DSOP_Méthodes_Service Transport A_R_VF": "Service_Transport_Aller_Retour",
    "DSOP_Méthodes_Annulation dossier_VF": "Actions_ANNULATION_DOSSIER",
    "DSOP_Méthodes_Service Retour DC Proche_VF": "Service_Retour_DC_Proche",
    "DSOP_Méthodes_Ouverture dossier sur appel du gestionnaire_VF": "Ouverture_dossier_Sur_appel_du_gestionnaire",
    "DSOP_METHODES_Service Voyage AR d'un proche_VF": "Service_Voyage_Aller_et_Retour_d_un_proche",
    "DSOP_Méthodes_Service Transports répétitifs_VF": "Service_Transports_repetitifs",
    "DSOP_Méthodes_Poursuivre un dossier Mis en attente_VF": "Poursuivre_un_dossier_Mis_en_attente",
    "DSOP_Méthodes_Accord PEC JA 50%_VF": "Accorder_une_PEC_JA_50",
    "DSOP_Méthodes_Décrocher un appel_VF": "Decrocher_un_appel",
    "DSOP_METHODES_Service Garanties Hors Enveloppe_VF": "Service_Garanties_Hors_Enveloppe",
    "DSOP_Méthodes_Prise de RV avec le Travailleur Social_VF": "Prise_de_RV_avec_le_Travailleur_Social",
    "DSOP_Méthodes_Zone Responsable V3.9_VF": "La_zone_Responsable",
    "DSOP_Méthodes_Accident_VF": "Fait_generateur_ACCIDENT",
    "DSOP_Méthodes_ADO MAIF consignes Communication_VF": "ADO_MAIF_Consignes_Communication",
    "DSOP_Méthodes_Rechercher un membre_VF": "Rechercher_un_membre",
    "DSOP_Méthodes_Service Rapatriement de valides_VF": "Service_Rapatriement_de_valides",
    "DSOP_Méthodes_Formules ADO MAIF_VF": "MAIF_Formules_ADO",
    "DSOP_Méthodes_Type de tâches_VF": "Les_types_de_Taches",
    "DSOP_Méthodes_Formule Sollicitudes_VF": "MAIF_Formule_Sollicitudes",
    "DSOP_METHODES_Dispositif_Call_Back_Dossiers_différés_VF": "Dispositif_Call_Back_ou_Dossiers_differes",
    "DSOP_Méthodes_Ernesti_VF": "Partenaire_Ernesti",
    "DSOP_Méthodes_MAIF_VF": "MAIF_Les_differentes_formules",
    "DSOP_Méthodes_Détails dossier_VF": "Onglet_Details_Dossier",
    "DSOP_Méthodes_Rembourser un CESU_VF": "Rembourser_un_CESU",
    "DSOP_Méthodes_Mémo Assistance Psychologique_VF": "Memo_Assistance_Psychologique",
    "DSOP_Méthodes_Tableau indicatif  m² à nettoyer nb d'heures_VF": "Tableau_indicatif_des_heures_a_allouer_selon_m2_a_nettoyer",
    "DSOP_Méthodes_Service Renseignement_VF": "Service_Renseignement",
    "DSOP_Méthodes_Traiter un fax _ E-mail_VF": "Traiter_un_Fax_ou_un_E_mail",
    "DSOP_Méthodes_Trame Mail libre_ Demande d'informations complémentaires_VF": "Trame_Mail_libre_Demande_d_informations_complementaires",
    "DSOP_Méthodes_Appels sortants Prestataires_VF": "Activite_cellule_Appels_sortants_Prestataires",
    "DSOP_Méthodes_FAQ Digitalisation DI_VF": "FAQ_DI_Domicile_et_Mobile_Sante",
    "DSOP_Méthodes_Confidentialité_VF": "La_confidentialite_d_un_dossier_a_l_OSBV",
    "DSOP_Méthodes_Les personnes assistables_VF": "La_zone_Personnes_s_Assistable_s",
    "DSOP_Méthodes_Livraison Higgins V3.10.1_VF": "Livraison_Higgins_V3_10_1_du_12_fevrier_2025",
    "DSOP_Méthodes_Traitement Direct ou Accompagné_VF": "Traitement_Direct_ou_Accompagne",
    "DSOP_Méthodes_Conduite à l'école etou aux activités extra-scolaires MH_VF": "MH_AUXIA_Conduite_a_l_ecole_et_aux_activites_extra_scolaires",
    "DSOP_Méthodes_Refus service_VF": "Le_Refus_de_service",
    "DSOP_Méthodes_Les données du souscripteur_VF": "Les_Donnees_personnelles_du_Souscripteur",
    "DSOP_Méthodes_Accompagnement Budgétaire_VF": "Service_Accompagnement_Budgetaire",
    "DSOP_Méthodes_TELEASSISTANCE_ SERELIA_VF": "Teleassistance_SERELIA",
    "DSOP_Méthodes_Livmed's_VF": "Partenaire_Livmed_s",
    "DSOP_Méthodes_Reconnaissance de dette_VF": "Traiter_une_Reconnaissance_de_dette_a_l_OSBV",
    "DSOP_Méthodes_My Jugaad_VF": "Partenaire_My_Jugaad",
    "DSOP_Méthodes_Réception d'un Devis_VF": "Traiter_un_mail_contenant_un_Devis",
    "DSOP_Méthodes_Martinique_VF": "Renseigner_une_adresse_a_la_Martinique",
    "DSOP_Méthodes_Service E Learning_VF": "Service_E_Learning",
    "DSOP_Méthodes_Modification des Données_VF": "Modification_des_Donnees_Souscripteur",
    "DSOP_Méthodes_Fichier en Confiance Préalable_VF": "Fichier_en_Confiance_prealable",
    "DSOP_Méthodes_Service Déplacement Proche au chevet_VF": "Service_Deplacement_proche_chevet",
    "DSOP_Méthodes_Renseignements sans identification_VF": "Renseignements_sans_identification_Henner",
    "DSOP_Méthodes_Traiter un Fax _ E-mail inexploitable_VF": "Traiter_un_flux_inexploitable_fax_e_mail",
    "DSOP_Méthodes_SMS_VF": "Envoyer_un_SMS",
    "DSOP_Méthodes_Garantie Prévention Bilan_VF": "Garanties_Prevention_Bilan",
    "DSOP_Méthodes_Contrats du souscripteur_VF": "CONTRATS_DU_SOUSCRIPTEUR",
    "DSOP_Méthodes_Demande d'Assistance Digitale (DAD)_VF": "Traiter_une_Demande_d_Assistance_Digitale_DAD",
    "DSOP_METHODES_Expertise métier_VF": "Expertise_metier",
    "DSOP_Méthodes_Garde de l'aidé_VF": "Service_Garde_de_l_aide",
    "DSOP_Méthodes_Service Ass.Psychologique_VF": "Service_Ass_Psychologique",
    "DSOP_Méthodes_Méthode par Approche Différenciée_VF": "La_Methode_par_Approche_Differenciee",
    "DSOP_Méthodes_Créer un membre_VF": "CREER_UN_MEMBRE",
    "DSOP_Méthodes_SMS Promotion_VF": "Le_SMS_Promotion",
    "DSOP_METHODES_Fait générateur absent_VF": "Fait_generateur_absent",
    "DSOP_Méthodes_Livraison Higgins V3.6 du 15 novembre 2023_VF": "Livraison_Higgins_V3_6_du_15_novembre_2023",
    "DSOP_Méthodes_ADO MAIF_ Contrats _ Formules _ Plafonds_VF": "ADO_MAIF_Contrats_Formules_et_Plafonds",
    "DSOP_Méthodes_Service Transfert des enfants chez un Proche_VF": "Service_Transfert_des_enfants_chez_un_Proche",
    "DSOP_Méthodes_Délai de carence_VF": "Delai_de_carence",
    "DSOP_Méthodes_Maternité_VF": "Fait_generateur_Maternite",
    "DSOP_Méthodes_Mémo Justifs_ Pièces à fournir_VF": "Memo_Justifs_Les_pieces_a_fournir",
    "DSOP_Méthodes_Compta Prestataire_VF": "Flux_Operationnels_Prestataires_compta",
    "DSOP_Méthodes_Note assistance_VF": "Note_assistance",
    "DSOP_Méthodes_Dérogations sociales spécificités MH_VF": "MH_AUXIA_Derogations_sociales",
    "DSOP_Méthodes_Prolongation Aide-Ménagère_VF": "Prolongation_Aide_Menagere",
    "DSOP_Méthodes_Service_ Locat. Téléviseur_VF": "Service_Location_Televiseur",
    "DSOP_METHODES_Demande de Prise en charge en après-coup_VF": "Traiter_une_demande_de_Prise_en_charge_en_apres_coup",
    "DSOP_Méthodes_Service_ Hippothérapie_VF": "Service_Hippotherapie",
    "DSOP_Méthodes_Service Aide à l'emploi_VF": "Service_Aide_a_l_emploi",
    "DSOP_Méthodes_Guadeloupe_VF": "Renseigner_une_adresse_a_la_Guadeloupe",
    "DSOP_Méthodes_Mémo Réorientation sociale_VF": "Memo_Reorientation_sociale",
    "DSOP_Méthodes_Proche_VF": "Definition_d_un_Proche",
    "DSOP_Méthodes_Service_ Nettoyage du logement_VF": "Service_Nettoyage_du_logement",
    "DSOP_Méthodes_Actions situations de fragilités Hors contrat_VF": "Traiter_les_situations_de_fragilites_Hors_contrat",
    "DSOP_Méthodes_Aide au calcul d'un CESU_VF": "Aide_au_calcul_d_un_CESU",
    "DSOP_Méthodes_Garanties à promouvoir_VF": "Garanties_a_promouvoir",
    "DSOP_Méthodes_Enveloppes (en unités)_VF": "Ouvrir_un_dossier_avec_une_enveloppe_en_Unites",
    "DSOP_Méthodes_Traitement d'un justificatif_VF": "Ouvrir_un_dossier_Administratif",
    "DSOP_Méthodes_Accord médical _ MLD ou Immo _ 30j_VF": "Demander_un_CM_en_cas_de_MLD_ou_Immo_de_plus_de_30_jrs",
    "DSOP_Méthodes_Prise en charge Déplacement d'un proche au chevet_VF": "Prise_en_charge_du_Deplacement_d_un_proche_au_chevet",
    "DSOP_Méthodes_Mise en Attente d'un dossier_VF": "Fonctionnalite_Mise_en_attente_d_un_dossier",
    "DSOP_Méthodes_Aide à l'emploi - Moyen Aide à la création d'entreprise_VF": "Moyen_Aide_a_la_creation_entreprise",
    "DSOP_Méthodes_Trame Mail libre_ Refus_VF": "Trame_Mail_libre_Refus",
    "DSOP_Méthodes_Service Jardinage_VF": "Service_Jardinage",
    "DSOP_Méthodes_Situation de fragilités_VF": "Actions_suite_detection_d_une_Situation_de_fragilites",
    "DSOP_Méthodes_Code région d'Outre-Mer_VF": "Renseigner_une_adresse_en_Departement_et_Region_d_Outre_Mer",
    "DSOP_Méthodes_Enveloppe de services spécificités MH_VF": "MH_AUXIA_Enveloppes_de_services",
    "DSOP_Méthodes_Service_ Garde Malade_VF": "Service_Garde_Malade",
    "DSOP_METHODES_Courriers_VF": "Corbeille_des_courriers",
    "DSOP_Méthodes_Renseignement IJ-CYBER_VF": "Renseignement_IJ_CYBER",
    "DSOP_Méthodes_Périmètre d'intervention_VF": "Perimetre_d_intervention_domaine_Sante",
    "DSOP_Méthodes_Dossier Responsabilité Civile_Recours-Défense (RCDF)_VF": "ADO_MAIF_Dossier_Responsabilite_Civile_ou_Recours_Defense_RCDF",
    "DSOP_Méthodes_Noé Santé_VF": "Plateforme_Partenaires_Clients_Noe_Sante",
    "DSOP_Méthodes_Enrôlement ROC_VF": "Realiser_l_enrolement_ROC",
    "DSOP_METHODES_GENERIQUE_Check_list_attestation_d_intervention_VF": "Check_list_attestation_d_intervention_OSBV",
    "DSOP_Méthodes_Service_ Ouverture Domicile_VF": "Service_Ouverture_Domicile",
    "DSOP_Méthodes_Service Coach Retraite_VF": "Service_Coaching_retraite",
    "DSOP_Méthodes_OXILIA_VF": "OXILIA",
    "DSOP_Méthodes_Carence Réseau Domicile_VF": "Traiter_une_Carence_Reseau_Domicile",
    "DSOP_Méthodes_Gérer un courrier reçu_VF": "Gerer_un_courrier_recu",
    "DSOP_Méthodes_Répertoire numéros internes_VF": "Repertoire_numeros_internes",
    "DSOP_Méthodes_Livraison Higgins du 18 avril 2023_VF": "Livraison_Higgins_V3_3_du_18_avril_2023",
    "DSOP_Méthodes_Protection_des_donnees_WIKI_VF": "Protection_des_donnees_a_l_OSBV",
    "DSOP_Méthodes_Refus multiples Aide Ménagère_VF": "Refus_multiples_Aide_Menagere",
    "DSOP_Méthodes_Onglet Données techniques_VF": "Onglet_Donnees_techniques",
    "DSOP_Méthodes_Renseignement Téléassistance-Pers_VF": "Renseignement_Teleassistance_Pers",
    "DSOP_Méthodes_Service Portage d'espèces_VF": "Service_Portage_d_especes",
    "DSOP_Méthodes_Codification des tâches_VF": "Codifications_des_taches",
    "DSOP_Méthodes_Prise en charge d'un Rapatriement de corps_VF": "Aide_au_calcul_de_Prise_en_charge_d_un_Rapatriement_de_corps",
    "DSOP_Méthodes_Annulation de commande dans le cadre d'un service Multi-formules_VF": "Annulation_de_commande_dans_le_cadre_d_un_service_Multi_Formules",
    "DSOP_METHODES_GENERIQUE_Propos_suicidaires_VF": "Propos_suicidaires",
    "DSOP_Méthodes_Entretien des tombes_VF": "Service_Entretien_des_tombes",
    "DSOP_Méthodes_Justif_ Infos manquantes_VF": "Traiter_un_justificatif_avec_des_informations_manquantes",
    "DSOP_Méthodes_Souscripteur _ Personne Physique_VF": "Souscripteur_Personne_Physique",
    "DSOP_Méthodes_Ouverture dossier_ Activité Chien_Chat_VF": "Ouverture_dossier_Activite_Chien_Chat",
    "DSOP_Méthodes_Service Consommateurs_VF": "Le_service_Consommateurs",
    "DSOP_Méthodes_Service Accompagnement suite décès_VF": "Service_Accompagnement_suite_deces",
    "DSOP_Méthodes_Renseignement Juridique Vie Pratique_VF": "Renseignement_Juridique_Vie_Pratique",
    "DSOP_Méthodes_Service_ Auxiliaire de Vie_VF": "Service_Auxiliaire_de_Vie",
    "DSOP_Méthodes_Formule Prévoyance Pro_VF": "MAIF_Formule_Prevoyance_Pro",
    "DSOP_Méthodes_Service_ Aide Humaine_VF": "ADO_MAIF_Service_Aide_Humaine",
    "DSOP_METHODES_GENERIQUE_Reclamation_et_mecontentement oral_VF": "Traiter_une_reclamation_ou_un_mecontentement_oral_sur_Higgins_Sante",
    "DSOP_Méthodes_Multi-formules_VF": "Multi_Formules",
    "DSOP_Méthodes_Immobilisation au domicile_VF": "La_zone_Immobilisation_au_Domicile",
    "DSOP_Méthodes_Service simplifié Aide Ménagère_VF": "Service_Aide_Menagere_en_mode_simplifie",
    "DSOP_Méthodes_Trame Mail libre_ Comportement Inapproprié avec accord JA_VF": "Trame_Mail_libre_Comportement_Inapproprie_avec_accord_JA",
    "DSOP_Méthodes_Tâches DI_VF": "Traiter_une_Tache_DI_par_la_Cellule_Appels_Sortants",
    "DSOP_Méthodes_Prolongation Soutien Scolaire_VF": "Prolongation_Soutien_Scolaire",
    "DSOP_Méthodes_Codifications_VF": "Codifications_dans_les_communications",
    "DSOP_Méthodes_Moyen_ Frais de Route_VF": "Moyen_Frais_de_Route",
    "DSOP_Méthodes_Zone Situation de fragilité_VF": "La_zone_Situation_de_fragilite",
    "DSOP_Méthodes_Application des clauses et règles contractuelles_VF": "Application_des_clauses_et_regles_contractuelles_a_l_OSBV",
    "DSOP_Méthodes_Types de justificatifs_VF": "Les_deux_types_de_justificatifs",
    "DSOP_Méthodes_Commandes_VF": "Commandes",
    "DSOP_Méthodes_Directions des Opérations Déplacement_VF": "Direction_des_Operations_Deplacement",
    "DSOP_Méthodes_Annuler un Fax _ E-mail_VF": "Annuler_un_Fax_ou_un_E_mail",
    "DSOP_Méthodes_Bordereaux_VF": "BORDEREAUX",
    "DSOP_Méthodes_Aide à l'emploi - Moyen Emploi mutation_VF": "MOYEN_EMPLOI_MUTATION",
    "DSOP_Méthodes_Renseignements en mode Raccourci_VF": "Renseignements_en_mode_Raccourci",
    "DSOP_Méthodes_Mémo Soutien Scolaire_VF": "Memo_Soutien_Scolaire",
    "DSOP_Méthodes_Attestation Intervention (ou non-intervention)_VF": "Generer_une_Attestation_d_Intervention_ou_de_non_intervention",
    "DSOP_Méthodes_Groupe responsable_VF": "La_zone_Groupe_Responsable",
    "DSOP_Méthodes_Annulation d'une commande_VF": "Annulation_d_une_commande",
    "DSOP_Méthodes_Le rebond_VF": "Le_Rebond_en_cas_de_refus",
    "DSOP_METHODES_DI DOMICILE_VF": "DI_DOMICILE",
    "DSOP_Méthodes_Gestion émotionnelle des appels difficiles_VF": "Dispositif_Gestion_emotionnelle_des_appels_difficiles",
    "DSOP_METHODES_Garanties Coaching_VF": "Garanties_Coaching",
    "DSOP_Méthodes_Suivi Digital des Enveloppes_VF": "Suivi_Digital_des_Enveloppes",
    "DSOP_Méthodes_Entité de facturation_VF": "Retrouver_l_entite_de_facturation_sur_Higgins_Sante",
    "DSOP_Méthodes_Carence Réseau Taxi Vsl Ambulance_VF": "Carence_Reseau_Taxi_Vsl_Ambulance",
    "DSOP_Méthodes_MH - Auxia_VF": "MH_Auxia",
    "DSOP_Méthodes_Client à n° unique_VF": "CLIENT_Mutuelle_a_ndeg_unique",
    "DSOP_Méthodes_Coaching Motivationnel (Acco. Prévention)_VF": "Prestation_Coaching_Motivationnel",
    "DSOP_Méthodes_Service_ Aide aux devoirs_VF": "Service_Aide_aux_devoirs",
    "DSOP_Méthodes_Mémo mails vers Prestataires_VF": "Memo_mails_vers_Prestataires",
    "DSOP_Méthodes_Flux inexploitable en provenance de DOMPLUS_VF": "Flux_inexploitable_en_provenance_de_DOMPLUS",
    "DSOP_Méthodes_Formules Obsèques groupe MACIF_VF": "Service_Prise_en_charge_d_obseques",
    "DSOP_Méthodes_Digitalisation Demande d'Intervention_VF": "Digitalisation_Demande_d_Intervention",
    "DSOP_Méthodes_Adresse postale_VF": "ADRESSE_POSTALE",
    "DSOP_Méthodes_Enrôlement_ Compléter les actions dans le fichier Excel de suivi_VF": "Enrolement_Completer_les_actions_dans_le_fichier_Excel_de_suivi",
    "DSOP_Méthodes_Nos prestataires funéraires_VF": "Nos_prestataires_funeraires",
    "DSOP_Méthodes_Protection des données de santé_VF": "Protection_des_donnees_de_sante",
    "DSOP_Méthodes_Garanties Activités Physiques Adaptées_VF": "Service_Activites_Physiques_Adaptees",
    "DSOP_Méthodes_Sollicitations réseau DPV (prestations d'aide à domicile)_VF": "Solliciter_le_reseau_DPV_prestations_d_aide_a_domicile",
    "DSOP_Méthodes_Documents_VF": "Bibliotheque_des_Documents_sortants",
    "DSOP_Méthodes_Solidarité coups durs_VF": "Solidarite_coups_durs",
    "DSOP_Méthodes_Références Externes_VF": "Onglet_References_Externes",
    "DSOP_Méthodes_Service_ Info. Diététique_VF": "Service_Info_Dietetique",
    "DSOP_Méthodes_Renseignement Aide Naissance_VF": "Renseignement_Aide_Naissance",
    "DSOP_Méthodes_Justificatif recevable_VF": "Definition_d_un_Justificatif_recevable",
    "DSOP_Méthodes_Plateforme Conseil et Orientation_VF": "Plateforme_Conseil_et_Orientation",
    "DSOP_Méthodes_Sourds et malentendants Traitement via plateau DOD_VF": "Sourds_et_malentendants_Traitement_via_plateau_DOD",
    "DSOP_Méthodes_Prestations bien être_VF": "Service_Prestations_bien_etre",
    "DSOP_Méthodes_Renseignement Assurance Générique_VF": "Renseignement_Assurance_Generique",
    "DSOP_Méthodes_Annuler un courrier_VF": "Annuler_un_courrier_numerise",
    "DSOP_Méthodes_Cyber_VF": "Fait_generateur_Cyber",
    "DSOP_Méthodes_Service Conduite à l'Ecole_VF": "Service_Conduite_a_l_Ecole",
    "DSOP_Méthodes_Service Courrier et Numérisation_VF": "Service_Courrier_et_Numerisation",
    "DSOP_Méthodes_Refus _ récla_VF": "Onglet_Refus_Recla",
    "DSOP_Méthodes_Traitement accompagné_VF": "Effectuer_un_Traitement_accompagne",
    "DSOP_Méthodes_Déverrouiller un dossier_VF": "Deverrouiller_un_dossier_sur_Higgins_Sante",
    "DSOP_Méthodes_Prise en charge de l'intervenant habituel_VF": "Prendre_en_charge_l_intervenant_habituel",
    "DSOP_Méthodes_SMR ≠ Hospi (ex-Application Aide Ménagère)_VF": "SMR_Hospi_ex_Application_Aide_Menagere",
    "DSOP_Méthodes_Glossaire_VF": "Glossaire_Higgins_Sante",
    "DSOP_Méthodes_Codes Rousseau_VF": "Codes_Rousseau_partenaire_Sante",
    "DSOP_Méthodes_Particularité Vigilance_VF": "Particularite_Vigilance",
    "DSOP_Méthodes_Exclure des informations dans les tableaux_VF": "Exclure_des_informations_dans_les_tableaux",
    "DSOP_Méthodes_Mise à jour de l'enveloppe d'unités_VF": "Mise_a_jour_de_l_enveloppe_en_unites",
    "DSOP_Méthodes_Les services d'accompagnement de la PiMS_VF": "Les_services_d_accompagnement_de_la_PiMS",
    "DSOP_Méthodes_Asynchrone_VF": "Traiter_un_flux_Asynchrone",
    "DSOP_Méthodes_Trame Mail libre_ Demande de documents complémentaires_VF": "Trame_Mail_libre_Demande_de_documents_complementaires",
    "DSOP_Méthodes_Enveloppe d'unités_VF": "L_enveloppe_en_unites",
    "DSOP_Méthodes_Garde de nuit par un étudiant en santé_VF": "Prestation_Garde_de_nuit_par_un_etudiant_en_sante",
    "DSOP_Méthodes_Renseignements en mode Classique_VF": "Renseignements_en_mode_Classique",
    "DSOP_Méthodes_trame demande CM Immo sup. 30 jours_VF": "Trame_Mail_libre_Demande_CM_Immo_sup_30_jours",
    "DSOP_Méthodes_Service Livraison de courses_VF": "Service_Livraison_de_courses",
    "DSOP_Méthodes_Mémo Tarifs horaires_VF": "Memo_Tarifs_horaires",
    "DSOP_Méthodes_Modalités de remboursement_ (document)_VF": "Emettre_le_flux_Modalites_de_remboursement",
    "DSOP_Méthodes_Gestion des dates_VF": "Gestion_des_dates",
    "DSOP_Méthodes_Dossiers multiples_VF": "Dispositif_Dossiers_multiples",
    "DSOP_Méthodes_Garanties Transport_VF": "Garanties_Transport",
    "DSOP_Méthodes_Corbeille d'arrivée_VF": "Corbeille_d_arrivee",
    "DSOP_Méthodes_Saveurs et Vie_VF": "Saveurs_et_Vie",
    "DSOP_Méthodes_Malakoff Autonomie +_VF": "Traiter_une_demande_Malakoff_Autonomie_Plus",
    "DSOP_Méthodes_Clore une tâche_VF": "Clore_une_tache",
    "DSOP_Méthodes_Raccourcis clavier pour le CTI_VF": "Raccourcis_clavier_CTI_sur_Higgins_Sante",
    "DSOP_Méthodes_Imputation en devises étrangères_VF": "Imputer_en_devises_etrangeres",
    "DSOP_Méthodes_Formule ADO Ergo_TSO Hors sinistre_VF": "MAIF_Formule_ADO_Ergo_TSO_Hors_sinistre",
    "DSOP_Méthodes_Qualité_VF": "La_zone_Qualite",
    "DSOP_Méthodes_Service_ Garde d'Ascendant_VF": "Service_Garde_d_Ascendant",
    "DSOP_Méthodes_IMATECH_VF": "IMATECH",
    "DSOP_Méthodes_Service_ Fermeture Domicile_VF": "Service_Fermeture_Domicile",
    "DSOP_Méthodes_Bouton  Copier_VF": "Fonctionnalite_du_bouton_COPIER",
    "DSOP_Méthodes_Direction des Affaires Juridiques_VF": "Direction_des_Affaires_Juridiques",
    "DSOP_Méthodes_Vue Souscripteur 360°_VF": "Vue_Souscripteur_360deg",
    "DSOP_Méthodes_Service_ Recueil des besoins_VF": "Service_Recueil_des_besoins",
    "DSOP_Méthodes_Service Aide-Ménagère _ Aide à domicile_VF": "Service_Aide_a_domicile_Aide_menagere",
    "DSOP_Méthodes_Recherche Souscripteur_VF": "Rechercher_un_Souscripteur",
    "DSOP_METHODES_Garantie Extra-contractuelle Exception_VF": "Garantie_Extra_contractuelle_et_Exception",
    "DSOP_Méthodes_La zone Quantité_VF": "La_zone_Quantite",
    "DSOP_Méthodes_Contrôle des droits_VF": "EFFECTUER_UN_CONTROLE_DES_DROITS",
    "DSOP_Méthodes_Guyane_VF": "Renseigner_une_adresse_en_Guyane",
    "DSOP_Méthodes_Moyen_ Indemnités de Déplacement_VF": "Moyen_Indemnites_de_Deplacement",
    "DSOP_Méthodes_Prévention Troubles Musculo-Squelettique_VF": "Service_Troubles_Musculo_Squelettique",
    "DSOP_Méthodes_N° de LR déjà utilisé_VF": "Reference_courrier_ndeg_de_LR_deja_utilisee",
    "DSOP_Méthodes_Habitation_VF": "Orienter_une_demande_concernant_l_Habitation",
    "DSOP_Méthodes_Sourds et Malentendants Traitement par SMS_VF": "Sourds_et_malentendants_Traitement_par_SMS",
    "DSOP_Méthodes_Maladie Longue Durée_VF": "Maladie_Longue_Duree",
    "DSOP_Méthodes_Moyen Taxi_VF": "Moyen_Taxi",
    "DSOP_Méthodes_Formules Obsèques_VF": "Traiter_une_formule_Obseques",
    "DSOP_Méthodes_Spécificités Ouvertures dossier_VF": "Ouverture_dossier_Specificites",
    "DSOP_Méthodes_IMA S@NTE_VF": "Le_portail_IMA_S_NTE",
    "DSOP_Méthodes_Catégorie de dossier_VF": "La_zone_CATEGORIE_DE_DOSSIER",
    "DSOP_Méthodes_Trame Mail libre_ Demande de contact téléphonique_VF": "Trame_Mail_libre_Demande_de_contact_telephonique",
    "DSOP_Méthodes_Garantie Service Commande_VF": "Presentation_des_garanties_autorisees",
    "DSOP_Méthodes_Frais antérieurs engagés par la MAIF_VF": "Gerer_les_frais_anterieurs_engages_par_la_MAIF",
    "DSOP_Méthodes_Appel assistante sociale seule_VF": "Traiter_l_appel_d_une_assistante_sociale_seule",
    "DSOP_Méthodes_Service_ Interprète Langue des Signes Française_VF": "Service_Interprete_Langue_des_Signes_Francaise",
    "DSOP_Méthodes_Conseil Social MH_VF": "MH_AUXIA_Conseil_Social",
    "DSOP_Méthodes_Service_ Garde d'Enfant_VF": "Service_Garde_d_Enfant",
    "DSOP_Méthodes_Lettre Personnalisée_VF": "Lettre_Personnalisee",
    "DSOP_Méthodes_La zone bénéficiaire de la commande_VF": "La_zone_beneficiaire_de_la_commande",
    "DSOP_Méthodes_Désarchivage d'un courrier_VF": "Demander_le_desarchivage_d_un_courrier",
    "DSOP_Méthodes_Codification des Flags_VF": "Codifications_des_Flags",
    "DSOP_Méthodes_Trame demande CM MLD_VF": "Trame_Mail_libre_Demande_CM_MLD",
    "DSOP_Méthodes_Service Rapatriement Corps en Terre d'origine_VF": "Service_Rapatriement_de_Corps_en_Terre_d_origine",
    "DSOP_Méthodes_Requalifier un Fax _ E-mail _ DRD_VF": "Requalifier_un_Fax_E_mail_une_DRD",
    "DSOP_Méthodes_Bonnes pratiques_ Protection des données_VF": "Bonnes_pratiques_Protection_des_donnees_a_l_OSBV",
    "DSOP_Méthodes_Avis de prélèvement automatique_VF": "Avis_de_prelevement_automatique",
    "DSOP_Méthodes_Service Soutien Scolaire_VF": "Service_Soutien_Scolaire",
    "DSOP_Méthodes_Mise en relation_VF": "Garantie_Mise_en_relation",
    "DSOP_Méthodes_Répertoire téléphonique_VF": "Repertoire_telephonique",
    "DSOP_Méthodes_Medicalib_VF": "Medicalib_partenaire_Sante",
    "DSOP_Méthodes_Rattacher un fax _ E-mail_VF": "Rattacher_un_fax_E_mail",
    "DSOP_Méthodes_Lettres types_VF": "Repertoire_Lettres_types_Sante",
    "DSOP_Méthodes_Mayotte_VF": "Renseigner_une_adresse_a_Mayotte",
    "DSOP_Méthodes_Lieu d'intervention_VF": "Les_lieux_d_intervention",
    "DSOP_Méthodes_Mémo Conduite à l'école_VF": "Memo_Conduite_a_l_ecole",
    "DSOP_Méthodes_Reporter une tâche_VF": "Reporter_une_tache",
    "DSOP_Méthodes_Souscripteur _ Personne Morale_VF": "Souscripteur_Personne_Morale",
    "DSOP_Méthodes_BPCE Vie_VF": "BPCE_Vie",
    "DSOP_Méthodes_Service Extra-C Mut_VF": "Service_Extra_C_Mut_MPE",
    "DSOP_Méthodes_Horaires d'intervention de nos prestataires_VF": "Horaires_d_intervention_de_nos_prestataires",
    "DSOP_Méthodes_Trame Mail libre_ Date de naissance manquante_VF": "Trame_Mail_libre_Date_de_naissance_manquante",
    "DSOP_Méthodes_Direction des Opérations Médicales et Santé, Bien-vivre_VF": "Direction_des_Operations_Medicales_et_Sante_Bien_vivre",
    "DSOP_Méthodes_Transfert en interne ou externe_VF": "Transferer_un_appel_en_interne_ou_en_externe",
    "DSOP_Méthodes_Acco examens médicaux dans l'enveloppe_VF": "Specificite_Acco_examens_medicaux_au_sein_d_une_enveloppe",
    "DSOP_Méthodes_Les données complémentaires_VF": "Renseigner_les_Donnees_complementaires",
    "DSOP_Méthodes_Livraison Higgins du 8 juin 2022_VF": "Livraison_Higgins_du_8_juin_2022",
    "DSOP_Méthodes_Les SMS automatiques_VF": "Les_SMS_automatiques",
    "DSOP_Méthodes_Souscripteur _VIP__VF": "Le_Souscripteur_VIP",
    "DSOP_Méthodes_Workplace Options_VF": "Workplace_Options",
    "DSOP_Méthodes_Imputation automatisée par RPA_VF": "Imputation_automatisee_par_RPA",
    "DSOP_Méthodes_Directions des Opérations Médicales et Etranger_VF": "Directions_des_Operations_Medicales_et_Etranger",
    "DSOP_Méthodes_Enrôlement Deuil et invalide_VF": "Realiser_l_enrolement_Deuil_et_invalide",
    "DSOP_Méthodes_Service_ PEC des Animaux_VF": "Service_PEC_des_Animaux",
    "DSOP_Méthodes_Mettre à jour la Corbeille_VF": "Mettre_a_jour_la_Corbeille",
    "DSOP_Méthodes_Saint Martin_VF": "Renseigner_une_adresse_a_Saint_Martin",
    "DSOP_Méthodes_Téléconsultation_VF": "Teleconsultation_par_IMA_S_NTE",
    "DSOP_Méthodes_Equiphoria_VF": "Partenaire_Equiphoria",
    "DSOP_Méthodes_Ergo - TSO_VF": "Les_Ergo_TSO",
    "DSOP_Méthodes_Enrôlement_ Ouverture du dossier Higgins_VF": "Enrolement_Ouverture_du_dossier_Higgins",
    "DSOP_Méthodes_Attribuer un n° LR à un fax _ E-mail_VF": "Attribuer_un_ndeg_LR_a_un_Fax_ou_un_E_mail",
    "DSOP_Méthodes_Traiter une LR version numérisée_VF": "Traiter_courrier_numerise",
    "DSOP_Méthodes_Réinitialiser l'affectation_VF": "Reinitialiser_l_affectation",
    "DSOP_Méthodes_Compta Sociétaires_VF": "Flux_Operationnels_Clients_Compta_Societaires",
    "DSOP_METHODES_Connexion Téléphonie Manuelle_VF": "Procedure_Connexion_manuelle_a_la_telephonie",
    "DSOP_Méthodes_Évènement traumatisant_VF": "Fait_generateur_Evenement_traumatisant",
    "DSOP_Méthodes_Ouverture dossiers_ Service à la Personne_VF": "Ouverture_dossier_Formules_Service_a_la_Personne",
    "DSOP_Méthodes_Identification spécificités MH_VF": "MH_AUXIA_Specificites_d_identification",
    "DSOP_METHODES_GENERIQUE_Assistance_pour_salarie_IMA_ou_proche_VF": "Assistance_pour_salarie_IMA_ou_proche_a_l_OSBV",
    "DSOP_Méthodes_Aide-mémoire_VF": "Liste_des_Memos",
    "DSOP_Méthodes_Demandeur Client Grand Compte_VF": "Demandeur_Client_Grand_Compte",
    "DSOP_Méthodes_Livraison Higgins du 05 octobre 2023_VF": "Livraison_Higgins_V3_5_du_05_octobre_2023",
    "DSOP_Méthodes_Cloisonnement Clients_VF": "CLOISONNEMENT_CLIENTS",
    "DSOP_Méthodes_Service Conseil social (Quest_rép)_VF": "Service_Conseil_social_Quest_rep",
    "DSOP_Méthodes_Reprise dossier MAIF_VF": "MAIF_Reprise_dossier",
    "DSOP_Méthodes_Service Rapatriement Corps_VF": "Service_Rapatriement_Corps",
    "DSOP_Méthodes_Plateforme Interdisciplinaire Médico-Sociale (PIMS)_VF": "La_Plateforme_Interdisciplinaire_Medico_Sociale_PIMS",
    "DSOP_Méthodes_Fiche Personne assistable_VF": "Fiche_Personne_s_assistable_s",
    "DSOP_Méthodes_Digitalisation Conduite à l'école_VF": "Formulaire_digital_Conduite_a_l_ecole",
    "DSOP_Méthodes_Réseau PAD_VF": "Le_Reseau_DOD",
    "DSOP_Méthodes_L'identification_VF": "L_identification_a_l_OSBV",
    "DSOP_Méthodes_Traitement direct_VF": "Effectuer_un_Traitement_direct",
    "DSOP_Méthodes_Contrôle des droits KO_VF": "CONTROLE_DES_DROITS_KO",
    "DSOP_Méthodes_BAL_VF": "Boite_Aux_Lettres_BAL_Reseau",
    "DSOP_Méthodes_Tâches_VF": "Les_Taches",
    "DSOP_Méthodes_Créer souscripteur_VF": "CREER_SOUSCRIPTEUR",
    "DSOP_Méthodes_Relation Santé _ Accompagnement Parcours de Vie_VF": "Relation_Sante_Accompagnement_Parcours_de_Vie",
    "DSOP_Méthodes_Service Avance F.Obsèques_VF": "Service_Avance_F_Obseques",
    "DSOP_Méthodes_Filtrer les informations dans les tableaux_VF": "Filtrer_les_informations_dans_les_tableaux",
    "DSOP_Méthodes_Les Garanties autorisées_VF": "Les_Garanties_autorisees",
    "DSOP_METHODES_Faits Générateurs_VF": "Les_Faits_Generateurs",
    "DSOP_Méthodes_Le pré-dossier_VF": "Le_Pre_dossier",
    "DSOP_Méthodes_Logement insalubre_VF": "Logement_insalubre",
    "DSOP_Méthodes_Sans fait générateur_VF": "Fait_generateur_Aucun",
    "DSOP_Méthodes_Perte d'Autonomie_VF": "Fait_generateur_Perte_d_Autonomie",
    "DSOP_Méthodes_Service Livraison de Médicaments_VF": "Service_Livraison_de_Medicaments",
    "DSOP_Méthodes_Renseignement Obsèques organisées_VF": "Renseignement_Obseques_organisees",
    "DSOP_Méthodes_Date de prise de connaissance_VF": "Date_de_prise_de_connaissance",
    "DSOP_Méthodes_Transports pour soins_VF": "ADO_MAIF_Garantie_Transports_pour_soins",
    "DSOP_Méthodes_Onglet Données restituées_VF": "Onglet_Donnees_restituees",
    "DSOP_Méthodes_Trame Gel des avoirs_VF": "Trame_Mail_libre_Gel_des_avoirs",
    "DSOP_Méthodes_Bilan Situationnel_VF": "Service_Bilan_situationnel",
    "DSOP_Méthodes_Imputation supérieure à 1500,00 €_VF": "Imputation_superieure_a_1500_00_EUR",
    "DSOP_Méthodes_Contrôle des droits OK_VF": "CONTROLE_DES_DROITS_OK",
    "DSOP_Méthodes_Livraison Higgins V3.2 du 9 novembre 2022_VF": "Livraison_Higgins_V3_2_du_9_novembre_2022",
    "DSOP_Méthodes_Date de survenance erronée_VF": "Date_de_survenance_erronee",
    "DSOP_Méthodes_Téléconsulation MH_VF": "MH_AUXIA_Reorienter_vers_la_Teleconsulation",
    "DSOP_Méthodes_Formule Efficience Santé_VF": "MAIF_Formule_Efficience_Sante",
    "DSOP_METHODES_Garanties Obsèques_VF": "Garanties_Obseques",
    "DSOP_Méthodes_Service Mise en Rel.Prest_VF": "Service_Mise_en_Rel_Prest",
    "DSOP_Méthodes_Droit d'accès aux données personnelles_VF": "Droit_d_acces_aux_donnees_personnelles",
    "DSOP_Méthodes_Pilotage de la Corbeille_VF": "Pilotage_de_la_Corbeille",
    "DSOP_Méthodes_Prolongation d'une commande_VF": "Prolongation_d_une_commande",
    "DSOP_Méthodes_Service_ Professionnel à Domicile_VF": "Service_Professionnel_a_Domicile",
    "DSOP_Méthodes_Ouverture sur mails gestionnaires MH_VF": "MH_AUXIA_Ouverture_sur_mails_Gestionnaires",
    "DSOP_Méthodes_Enrôlement_ Insertion des nouvelles lignes_VF": "Enrolement_Inserer_des_nouvelles_lignes",
    "DSOP_Méthodes_Gel des avoirs_VF": "Dispositif_Gel_des_avoirs",
    "DSOP_Méthodes_Notes_VF": "Les_Notes",
    "DSOP_Méthodes_Moyen Train_VF": "Moyen_Train",
    "DSOP_Méthodes_Garanties Service à la personne_VF": "Garanties_Service_a_la_personne",
    "DSOP_METHODES_GENERIQUE_Canaux_de_reception_des_justificatifs_VF": "Canaux_de_reception_des_justificatifs_a_l_OSBV",
    "DSOP_Méthodes_Renseignement Disparition de l'animal_VF": "Renseignement_Disparition_de_l_animal",
    "DSOP_Méthodes_Demande de Remboursement Digitale_VF": "Parcours_d_une_Demande_de_Remboursement_Digitale_DRD",
    "DSOP_Méthodes_Traiter le retour d'une tâche réseau Domicile_VF": "Traiter_le_retour_d_une_tache_reseau_Domicile",
    "DSOP_Méthodes_Gestion et Justificatifs_VF": "Gestion_et_Justificatifs",
    "DSOP_Méthodes_Service_ Conseil social_VF": "Service_Conseil_social",
    "DSOP_Méthodes_Infirmières ICS_VF": "Les_Infirmieres_ICS",
    "DSOP_Méthodes_Intervenants_VF": "Intervenants",
    "DSOP_Méthodes_Traiter une LR version papier_VF": "Traiter_un_courrier_papier",
    "DSOP_Méthodes_Demande de prolongation ADO MAIF_VF": "ADO_MAIF_Demande_de_prolongation",
    "DSOP_METHODES_Ariane_Surconsommation_VF": "Surconsommation",
    "DSOP_METHODES_Ariane_Dérogation - franchise KM_VF": "Managers_Mode_operatoire_Illimitee_22_05_2019_Application_garantie",
    "DSOP_METHODES_Ariane_Suivi de l'activité Coopération Assisteur par les managers_VF": "Suivi_de_l_activite_Cooperation_Assisteur_par_les_managers",
    "DSOP_METHODES_Ariane_Dossier VIP - Médiatisés - Indélicats - Débiteurs - Vigilance_VF": "Dossier_VIP_Mediatises_Indelicats_Debiteurs_Vigilance",
    "DSOP_METHODES_Ariane_Gel des avoirs_VF": "Managers_Procedure_metier_Illimitee_01_06_2022_Gestion",
    "DSOP_METHODES_Ariane_Réseau Animateurs_sectorisation_VF": "Managers_Procedure_metier_Illimitee_2024",
    "DSOP_METHODES_Ariane_Vigilance pays Process Teams_VF": "Vigilance_pays",
    "DSOP_METHODES_Ariane_Vigilance bénéficiaire_VF": "Vigilance_beneficiaire",
    "DSOP_METHODES_Ariane_Appels astreinte urgences SMACL_VF": "Managers_Procedure_metier_Illimitee_29_01_2019",
    "DSOP_METHODES_Ariane_Hot line loueurs en vigueur_VF": "Managers_Procedure_Metier_Illimitee_17_02_2025_Application_garantie",
    "DSOP_METHODES_Ariane_Procédure OKJ supérieure à 1500 euros_VF": "Managers_Procedure_metier_Illimitee_15_03_2022_Gestion",
    "DSOP_METHODES_Ariane_Prévention de la fraude_VF": "Manager_Procedure_metier_Illimitee_01_05_2021_Ouverture",
    "DSOP_Méthodes_Codes Refus_BALs_Suivis instantanés_VF": "Codes_refus_BALs_Suivis_Instantanes",
    "DSOP_Méthodes_Teambrain_VF": "Teambrain",
    "DSOP_Méthodes_Calculer une Garantie Multiple en JA JD sous HD_VF": "Tous_Mode_operatoire_Illimitee_25_11_2022_Gestion_Demande_de_remboursement",
    "DSOP_Méthodes_Travel Book 2024_VF": "Travel_book_2024",
    "DSOP_Méthodes_Assistance cumulative_VF": "L_assistance_cumulative",
    "DSOP_Méthodes_Process Tracking Véhicule PSA_VF": "Tous_Procedure_Metier_Illimitee_Renseignement_Appel_d_un_client_ayant_souscrit_a_l_option_tracking_qui_demande_la_geolocalisation_de_son_vehicule_suite_a_un_vol",
    "DSOP_METHODES_GENERIQUE_Abreviations_metier_VF": "Abreviations_metier",
    "DSOP_Méthodes_SELF_VF": "Self",
    "DSOP_Méthodes_Guide de la fiche de communication et du résumé_VF": "Guide_de_la_fiche_de_communication_ou_Note_et_du_resume",
    "DSOP_Méthodes_Surconsommation Assistance_VF": "Surconsommation_Assistance",
    "DSOP_METHODES_GENERIQUE_Dispositifs_de_reactivite_VF": "Dispositifs_de_reactivite",
    "DSOP_Méthodes_Tarif Autoroute_VF": "Tous_Reglementaire_Illimitee_30_08_2024_Application_Garanties_Demande_de_prise_en_charge_d_un_depannage_remorquage_sur_autoroute",
    "DSOP_Méthodes_Assistance routière survenance Royaume-Uni_VF": "Tous_Procedure_Metier_Illimite_Application_Garanties_Ouverture_d_un_dossier_avec_une_survenance_au_Royaume_Uni",
    "DSOP_METHODES_GENERIQUE_Conflit_d_interets_VF": "Assistance_au_profit_d_un_salarie_de_l_entreprise_ou_de_l_un_de_ses_proches",
    "DSOP_Méthodes_DOSSIERS INTERSITES_VF": "Dossiers_Intersites",
    "DSOP_Méthodes_Déclaration sur l'honneur au titre des Assistances Cumulatives_VF": "Declaration_sur_l_honneur_au_titre_des_Assistances_Cumulatives",
    "DSOP_Méthodes_Sourds Malentendants_VF": "Sourds_et_Malentendants",
    "DSOP_Méthodes_Effondrement d'immeuble_VF": "Effondrement_d_immeuble",
    "DSOP_Méthodes_Appels Police Gendarmerie Tiers_VF": "Appel_Police_Gendarmerie_Tiers",
    "DSOP_Méthodes_Situations hivernales ABC pratiques_VF": "Tous_Procedure_metier_05_01_2024_05_01_2024_Ouverture_Situations_hivernales",
    "DSOP_METHODES_GENERIQUE_Appels_GC_en_Assistance_VF": "Appel_d_un_Grand_Compte_en_Assistance",
    "DSOP_Méthodes_MAIF Habitation_VF": "MAIF_habitation_Descriptif_des_possibilites_de_traitement",
    "DSOP_METHODES_GENERIQUE_Codifications_Actualite_Dossier_VF": "Codifications_Actualite_Dossier",
    "DSOP_METHODES_MOBILITE_Recherche_linguiste_VF": "Tous_Procedure_metier_Illimitee_Application_des_garanties_Reception_d_un_appel_ou_mail_en_langue_etrangere",
    "DSOP_Méthodes_Fiche Renseignement_VF – Copie": "Renseignements",
    "DSOP_METHODES_GENERIQUE_BPCEAI_TRAITEMENT_DES_RENSEIGNEMENTS_CAC_ VF": "BPCEAI_Traitement_des_Renseignements_CAC",
    "DSOP_Méthodes_Véhicule retrouvé suite à vol_VF": "Vehicule_retrouve_suite_a_vol",
    "DSOP_Méthodes_Demandes PREST REMO_VF": "Tous_Procedure_Metier_Illimitee_01_02_2024_Application_garanties_Reception_d_une_demande_FORMS_d_un_prestataire",
    "DSOP_Méthodes_Mode opératoire de réservation avec The Treep_VF": "Tous_Mode_operatoire_Illimitee_27_09_2024_Application_garanties_Mise_en_oeuvre_d_un_rapatriement_ou_poursuite",
    "DSOP_Méthodes_Traitement du suivi des dossiers Coop_VF": "Tous_Procedure_Metier_Illimitee_19_12_2023_Application_garanties_Dossier_ouvert_a_la_demande_d_un_autre_assisteurs_faisant_partie_du_dispositif_de_Cooperation_Assisteur",
    "DSOP_Méthodes_Campagne  rappel constructeurs _ VF": "Campagne_de_rappel_airbags_Takata_Citroen_DS",
    "DSOP_Méthodes_Réclamations_VF": "Reclamations",
    "DSOP_Méthodes_Interlocuteurs DME_Consignes de nuit_VF": "Tous_Procedure_Metier_Illimitee_20_07_2018_Application_des_garanties_Consignes_de_nuit",
    "DSOP_METHODES_GENERIQUE_Dossier_VIP_VF": "Agent_de_maitrise_dossier_VIP",
    "DSOP_METHODES_GENERIQUE_Annulation_dossier_VF": "ANNULATION_D_UN_DOSSIER",
    "DSOP_Méthodes_Vérifications avant le traitement d’un flow Teams_VF": "Verifications_avant_le_traitement_d_un_flow_Teams",
    "DSOP_Méthodes_PDS sous MCS_VF": "Tous_Mode_operatoire_Illimitee_06_11_2024_Ouverture_Demande_de_remorquage_non_couvert_par_le_contrat",
    "DSOP_Méthodes_Absence de consultation médicale (NPC)_VF": "Tous_Mode_operatoire_Illimitee_04_12_2024_Application_Garanties_Dossier_medical",
    "DSOP_Méthodes_IMADirect_VF": "Tous_Mode_operatoire_Illimitee_27_01_2025_Applications_de_garanties",
    "DSOP_Méthodes_Aide à la décision DEPA-REMO_VF": "Aide_a_la_decision_DEPA_REMO",
    "DSOP_Méthodes_Appel destiné à un membre de la Direction_VF": "Appel_destine_a_un_membre_de_la_Direction",
    "DSOP_Méthodes_REMO Situation de contrainte + RELIV_VF": "Tous_Procedure_Metier_Illimite_08_01_2025_Application_de_garanties",
    "DSOP_Méthodes_Loi Montagne II_VF": "Tous_Procedure_Metier_06_11_2023_09_11_2023_Ouverture_Evenement_Zone_blanche",
    "DSOP_Méthodes_Le transfert d’appels pour déclaration de sinistre MAIF_VF": "Tous_Mode_operatoire_Illimitee_12_03_2021_Ouverture_Sinistre",
    "DSOP_Méthodes_Réserver un VREMP VLOC avec ENTERPRISE_VF": "Tous_Procedure_Metier_Depuis_le_18_04_2024_29_01_2025_Application_de_garanties",
    "DSOP_Méthodes_Transférer un appel sous Higgins_VF": "Transferer_un_appel_sous_Higgins",
    "DSOP_Méthodes_Dossier Prestataire_VF": "Dossier_Prestataire",
    "DSOP_Méthodes_Carnet de voyage 2024_VF": "Carnet_de_voyage_2024",
    "DSOP_Méthodes_Traiter un retour Enterprise_VF": "Service_Rouen_Cellule_USS_Enterprise_Procedure_metier_Depuis_le_01_06_2024_16_09_2024_Application_de_garanties",
    "DSOP_Méthodes_JOCKEYAGE_Tableau Recapitulatif_VF": "Jockeyage_Tableau_recapitulatif",
    "DSOP_Méthodes_Vers 100 des appels tracés_VF": "Vers_cent_pour_cent_des_appels_traces",
    "DSOP_Méthodes_La messagerie_VF": "La_messagerie",
    "DSOP_METHODES_GENERIQUE_Moyens_Justifs_Accord_Manager_VF": "Agent_de_maitrise_moyens_et_justifs",
    "DSOP_Méthodes_Modalités de facturation_VF": "Modalites_de_facturation_prestataire",
    "DSOP_METHODES_GENERIQUE_Appels_en_debordement_VF": "Tous_Procedure_metier_Illimitee_Ouverture_Appel_en_debordement",
    "DSOP_Méthodes_Accident de plongée_VF": "Tous_Procedure_Metier_Illimitee_05_08_2014_Ouverture_Dossier_medical",
    "DSOP_METHODES_MOBILITE_Evénements_au_Moyen_Orient_VF": "Tous_Procedure_Metier_Depuis_le_04_10_2024_Ouverture_Alerte_evenement_Moyen_Orient",
    "DSOP_Methodes_Traiter un Justificatif_VF": "Tous_Mode_operatoire_Illimitee_04_11_2024_Gestion_Beneficiaire_demande_un_remboursement",
    "DSOP_Méthodes_DI Mobile Taxi_VF": "DI_Mobile_Taxi",
    "DSOP_Méthodes_Rés@train_VF": "Tous_Mode_operatoire_Illimitee_31_07_2024_Application_garantie_Demande_de_rapatriement_poursuite_en_train",
    "DSOP_METHODES_GENERIQUE_Modification_resolution_ecran_Prod_VF": "Modification_resolution_ecran_en_Production",
    "DSOP_Méthodes_BeNomad_VF": "Tous_Mode_Operatoire_Illimitee_07_04_2023_Renseignement_Vehicules_electriques",
    "DSOP_METHODES_MOBILITE_Conflit_en_Ukraine_VF": "Tous_Procedure_Metier_Depuis_le_28_02_2022_20_11_2024_Ouverture_Evenement_en_lien_avec_le_Conflit_en_Ukraine",
    "DSOP_Méthodes_Reconnaissance de l'appelant_VF": "Reconnaissance_de_l_appelant",
    "DSOP_Méthodes_Réserver un hôtel avec CDS_VF": "Tous_Procedure_Metier_Depuis_le_09_06_2021_03_02_2025_Application_de_garanties",
    "DSOP_Méthodes_Demande d'intervention IMA vers Assisteurs_VF": "Tous_Procedure_Metier_Illimitee_14_06_2024_Applications_garanties_Besoin_de_faire_intervenir_un_assisteur_pour_la_prise_en_charge_d_un_vehicule",
    "DSOP_Méthodes_IMAconnect_VF": "IMAconnect",
    "DSOP_METHODES_GENERIQUE_BPCEAI_TRAITEMENT_DES_RENSEIGNEMENTS_VF": "BPCEAI_Traitement_des_Renseignements",
    "DSOP_Méthodes_Process AGA – Assistance Géolocalisée Autoroute sous Hi_VF": "Tous_Mode_operatoire_Illimitee_11_10_2024_Ouverture_Beneficiaire_sur_voie_reglementee",
    "DSOP_Méthodes_GENERIQUE_Informations Pays Travellers_VF": "Informations_Pays_Travellers",
    "DSOP_Méthodes_L'abandon du véhicule par son propriétaire_VF": "Abandon_du_vehicule_par_son_proprietaire",
    "DSOP_Méthodes_Demande d'intervention Assisteurs vers IMA sous HI_VF": "Tous_Procedure_Metier_Illimitee_23_10_2024_Application_Garanties_Demande_d_intervention_Assisteurs_vers_IMA",
    "DSOP_Méthodes_VIP_Indélicat_Vigilance_VF": "VIP_Indelicat_Debiteur_Vigilance",
    "DSOP_Méthodes_Procédure de traitement d'une demande Coopération Assisteur_VF": "Tous_Procedure_Metier_Illimitee_23_10_2024_Application_Garanties_Demande_d_intervention_d_un_autre_assisteur_vers_IMA_Demande_d_intervention_d_IMA_vers_un_autre_assisteur",
    "DSOP_Méthodes_Bordereaux_VF": "BORDEREAUX",
    "DSOP_Méthodes_BPCEAI_Incident_fichier_VF": "BPCEAI_Incident_fichier",
    "DSOP_Méthodes_Asynchrones Fax Mail_VF": "Traitement_d_un_fax_ou_mail_recu_en_asynchrone",
    "DSOP_Méthodes_Fauteuil roulant électrique_VF": "Fauteuil_roulant_electrique",
    "DSOP_Méthodes_Alerte Évènement_VF": "Tous_Procedure_Metier_Illimitee_11_10_2024_Ouverture_Des_la_creation_d_un_evenement",
    "DSOP_METHODES_MOBILITE_Cloisonnement_Clients_VF": "Cloisonnement_clients",
    "DSOP_Méthodes_Procédure de réservation d’un véhicule de location avec Rés@car_VF": "Tous_Mode_operatoire_Illimitee_12_06_2024_Application_garantie_Mise_en_oeuvre_d_un_vehicule_de_location",
    "DSOP_Méthodes_FAQ Réclamations orales_VF": "Reclamations_FAQ",
    "DSOP_Méthodes_PDS HAB sous Hi_VF": "La_PDS_Habitation_sous_Higgins",
    "DSOP_METHODES_GENERIQUE_Assisteurs_VF": "Liste_des_assisteurs",
    "DSOP_Méthodes_Les bonnes pratiques DEPA REMO_VF": "Tous_Procedure_Metier_Illimitee_15_05_2024_Application_garantie_Mise_en_oeuvre_d_un_DEPA_REMO",
    "DSOP_Méthodes_NOMADPEC_VF": "NOMADPEC",
    "DSOP_Méthodes_Appels administratifs_VF": "Appels_administratifs",
    "DSOP_Méthodes_Pré décla Déclaration de sinistre_VF": "Tous_Mode_operatoire_Illimitee_18_11_2024_Ouverture_Sinistre_blesse_accident_vehicule",
    "DSOP_Méthodes_Appels pour IMH_VF": "Appels_pour_IMH_MACIF_MAPA_AGPM_MATMUT_MATMUT_CO_MAE_BNP_Cardif_IARD",
    "DSOP_Méthodes_Vigilance 911 Dépannage_VF": "Tous_Procedure_Metier_Illimitee_Ouverture_Sollicitation_de_ce_prestataire_pour_une_prise_en_charge_de_depannage_ou_remorquage_en_apres_coup",
    "DSOP_METHODES_GENERIQUE_Appels malveillants_VF": "Appels_malveillants",
    "DSOP_METHODES_MOBILITE_Emeutes_Nouvelle_Calédonie_VF": "Tous_Procedure_Metier_Depuis_le_24_05_2024_27_05_2024_Ouverture_Alerte_evenement_Nouvelle_Caledonie",
    "DSOP_Méthodes_Procédure plateaux vers Module loueur_VF": "Tous_Procedure_Metier_Illimitee_17_01_2025_Application_garanties_Mise_en_oeuvre_d_un_VLOC",
    "DSOP_Méthodes_Consignes pour intempéries MCS_VF -": "Consignes_pour_intemperies_ABC_pratique_MCS",
    "DSOP_Méthodes_Rattachement des flux sans référence_VF": "RATTACHEMENT_DES_FLUX_SANS_REFERENCES",
    "DSOP_METHODES_GENERIQUE_Extra_Contractuel_VF": "Agent_de_maitrise_Extra_contractuel",
    "DSOP_Méthodes_Consignes pour intempéries HI_VF": "Consignes_pour_intemperies_ABC_pratique_HI",
    "DSOP_METHODES_GENERIQUE_Actualite_Dossier_VF": "Agent_de_maitrise_Actualite_dossier",
    "DSOP_Méthodes_Prévention de la fraude_VF": "Prevention_de_la_fraude",
    "DSOP_Méthodes_Ouverture sur appel autre assisteur_VF": "Tous_Procedure_Metier_Illimitee_19_07_2024_Application_garanties_Reception_d_une_demande_d_intervention_d_un_assisteur_en_dehors_de_la_Cooperation_Assisteurs",
    "DSOP_METHODES_GENERIQUE_Protection_des_donnees_VF": "Protection_des_donnees",
    "DSOP_Méthodes_Réservation d'avion pour un valide_VF": "Tous_Mode_operatoire_Illimitee_Application_de_garanties",
    "DSOP_Méthodes_Bonnes pratiques Loueurs_VF": "Tous_Procedure_Metier_Illimitee_15_05_2024_Application_Garanties_Mise_en_oeuvre_d_un_vehicule_de_location",
    "DSOP_METHODES_MOBILITE_Numeros_de_comptes_des_loueurs_VF": "Tous_Procedure_metier_Illimitee_23_07_2024_Application_garanties_Location_de_vehicule",
    "DSOP_Méthodes_Réservation VLOC Etranger (2024)_VF": "Reservation_VLOC_Etranger_2024",
    "DSOP_Méthodes_Grève SNCF_VF": "Tous_Procedure_Metier_Illimitee_29_08_2018_Application_Garantie_Besoin_de_mise_en_oeuvre_d_un_billet_de_train_alors_qu_une_greve_est_en_cours_a_la_SNCF",
    "DSOP_Méthodes_Réservation VLOC Etranger (2025)_VF": "Reservation_VLOC_Etranger",
    "DSOP_Méthodes_Véhicule sous séquestre à l’étranger_VF": "Tous_Procedure_metier_Illimitee_17_06_2024_Application_garantie_Vehicule_retrouve_a_l_etranger_suite_a_un_vol",
    "DSOP_Méthodes_Présentation WhatsApp Renault_VF": "Tous_Procedure_Metier_Illimitee_09_03_2022_Application_Garanties_Reception_d_un_sms_pour_un_client_Renault",
    "DSOP_Méthodes_Appels Survenance Autoroute_VF": "Tous_Procedure_Metier_Illimitee_30_05_2024_Ouverture_Survenance_autoroute",
    "DSOP_METHODES_IMANet_VF": "Tous_Procedure_Metier_Illimite_Application_Prestataire_depanneur_equipe_de_IMAnet",
    "DSOP_Méthodes_EURODRIVE_VF": "Tous_Procedure_Metier_Illimitee_08_02_2021_Ouverture_Dossier_constructeur",
    "DSOP_Méthodes_PDS_HAB_sous_MCS_VF": "La_PDS_Habitation_sous_MCS",
    "DSOP_Méthodes_Recherche Gardiennage_VF": "Recherche_Gardiennage_habitation",
    "DSOP_Méthodes - What 3 Words_VF": "Tous_Mode_operatoire_Illimitee_19_04_2023_Ouverture_Beneficiaire_ne_connait_pas_sa_localisation",
    "DSOP_Méthodes_PSA MyMarque_VF": "Tous_Procedure_Metier_Illimitee_16_09_2020_Ouverture_Activite_constructeur",
    "DSOP_Méthodes_FRAIS SECOURS SKI_VF": "DOD_Procedure_Metier_Depuis_le_21_02_2012_10_12_2024_Garanties_Patients_Frais_de_secours_en_montagne",
    "DSOP_Méthodes_Mandatement_transparent_VF": "Tous_Mode_Operatoire_Illimite_22_02_2017_Ouverture_MCS",
    "DSOP_Méthodes_Traçabilité lieu de livraison_VF": "Tracabilite_du_lieu_de_livraison",
    "DSOP_METHODES_GENERIQUE_Dossier_RCI_DAD_DAF_VF": "Ouverture_d_un_second_dossier_RCI_DAD_DAF_CAC",
    "DSOP_METHODES_GENERIQUE_Service_Consommateurs_VF": "Service_Consommateur",
    "DSOP_METHODES_GENERIQUE_Coordonnees_IMA_VF": "Coordonnees_IMA",
    "DSOP_METHODES_GENERIQUE_Comptabilite_Clients_et_Prestataires_VF": "Comptabilite_Clients_et_Prestataires",
    "DSOP_METHODES_MOBILITE_Bureau_Diagnostic_et_Estimation_VF": "Bureau_Diagnostic_et_Estimation_BDE",
    "DSOP_METHODES_GENERIQUE_SRGC_VF": "Service_Relations_Grands_Comptes_SRGC",
    "DSOP_METHODES_MOBILITE_Bureau_des_Transports_Terrestres_VF": "Bureau_des_Transports_Terrestres_BTT",
    "DSOP_METHODES_GENERIQUE_Interlocuteurs_DROM_VF": "Interlocuteurs_DROM",
    "DSOP_METHODES_GENERIQUE_Courrier_et_Numerisation_VF": "Service_Courrier_et_Numerisation",
    "DSOP_METHODES_GENERIQUE_Bureau_des_Transports_Aeriens_VF": "Bureau_des_Transports_Aeriens_BTA",
    "DSOP_METHODES_MOBILITE_Cellule_Frais_Medicaux_VF": "Tous_Mode_Operatoire_Illimite_23_08_2024_Application_des_garanties_Dossier_medical",
    "DSOP_METHODES_MOBILITE_Filiales_Internationales_VF": "Filiales_Internationales",
    "DSOP_METHODES_GENERIQUE_Contacter_la_Reference_Technique_VF": "Contacter_la_Reference_Technique",
    "DSOP_METHODES_HABITATION_Contacter_IMH_VF": "Contacter_IMH"}

reverse_mapping = {normalize_phrase(k).lower(): k for k, v in referentiel.items()}
def get_reference(key):
    normalize_key = normalize_phrase(key).lower()
    original_key = reverse_mapping.get(normalize_key)
    #print(f"test normalize : {normalize_key} => original : {original_key}")
    if original_key:
        return referentiel.get(original_key, "Clé non trouvée")
    return "Clé non trouvée"